# Generated by Django 3.1.2 on 2020-10-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201025_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='brief',
            field=models.TextField(default="Grab your viewers' attention using a brief introduction to the Blog"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
