# Generated by Django 3.1.2 on 2020-10-26 06:06

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201026_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
